### ISSUE TITLE
Firmware flash not working when space is in path

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#126]
```
DEBUG:root:C:\Program Files (x86)\ayab-windows-0.80\.\ayab\plugins\ayab_plugin\firmware\.\avrdude.exe -v -p atmega328p -C "C:\Program Files (x86)\ayab-windows-0.80\.\ayab\plugins\ayab_plugin\firmware\avrdude.conf" -c arduino -P COM31 -b115200 -D -Uflash:w:"C:\Program Files (x86)\ayab-windows-0.80\.\ayab\plugins\ayab_plugin\firmware\uno\kh910_uno_0-80.hex":i 
```
When I ran it, the problem was that I needed to put `"` around it and it worked fine:

```
"C:\Program Files (x86)\ayab-windows-0.80\.\ayab\plugins\ayab_plugin\firmware\.\avrdude.exe" -v -p atmega328p -C "C:\Program Files (x86)\ayab-windows-0.80\.\ayab\plugins\ayab_plugin\firmware\avrdude.conf" -c arduino -P COM31 -b115200 -D -Uflash:w:"C:\Program Files (x86)\ayab-windows-0.80\.\ayab\plugins\ayab_plugin\firmware\uno\kh910_uno_0-80.hex":i 
```

I suppose the first argument of the command line should be escaped properly.

**Comment by Adrienne200** [comment]
Oh, I missed this one on my previous pass through the fixed bugs. I'm still seeing it fail, Win7-64.
 
I hadn't noticed that I had been using no-space paths this whole time, so I never saw this issue. For comparison, I went back to 0.8 on XP32, added a space to the path; back then it failed with an error message.

In 0.9-RC4 in
C:\AYAB\AYAB-Windows 7\
instead of an error, it hangs.
When the path is C:\AYAB\AYAB-Windows7\, it flashes normally.

Log:
DEBUG:root:Loading AYAB from normal package structure.
DEBUG:root:Loading AYAB from normal package structure.
INFO:root:Plugin AYAB activated
INFO:root:Set enabled_plugin as <yapsy.PluginInfo.PluginInfo object at 0x030B23B0> - AYAB
DEBUG:root:C:\AYAB\AYAB-Windows 7\plugins\ayab_plugin\firmware\avrdude.exe -p atmega328p -c arduino -P COM4 -b115200 -D -Uflash:w:"C:\AYAB\AYAB-Windows 7\plugins\ayab_plugin\firmware\uno\kh910_uno_0-80.hex":i  -C C:\AYAB\AYAB-Windows 7\plugins\ayab_plugin\firmware\avrdude.conf
DEBUG:root:b"'C:\\AYAB\\AYAB-Windows' is not recognized as an internal or external command,\r\n"
DEBUG:root:b'operable program or batch file.\r\n'
DEBUG:root:b''
DEBUG:root:b''
<repeat for ever>

**Comment by Adrienne200** [comment]
This works now. Added a space to the path, firmware flash worked. OK to close.
0.9RC6 on Win7-64
