### ISSUE TITLE
Possibility to repeat rapport

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#144]
Add a GUI element which causes the current pattern to be knit as often as the currently chosen needle width allows.

**Comment by chris007de** [comment]
Solved by https://github.com/AllYarnsAreBeautiful/ayab-desktop/pull/251

**Comment by derchrisuk** [comment]
http://ayab-debug.s3-website.eu-central-1.amazonaws.com/

**Comment by Adrienne200** [comment]
The new Image Actions -> Repeat feature is working nicely, thank you. (Tested in post61 ahead of 0.95). But I have a few comments.
 - a reset or undo would be nice, to change your mind and go back to the image you started from.
 - the vertical repeat feature is technically redundant as we already have Infinite Repeat. But this means you can see better what it will look like repeated, so it does add value.
 - on Windows there's a question-mark icon which should lead to some help text. Did you intend to have some help, or should that icon be removed?
 - what should it do if you multiply it horizontally to more than 200 pixels wide? Currently it overflows the display in a weird way. But just chopping it at 200 might not be the right solution because there is also the ability to re-center it, what does anyone else think? Or maybe it's OK, users will learn not to multiply it much past 200.
And thanks for the shortcuts, if I find anything to question about them I'll log a separate issue.

**Comment by chris007de** [comment]
> - a reset or undo would be nice, to change your mind and go back to the image you started from.

For now you can just load the pattern again to reset. If this gets annoying, we'll open a separate issue for this in the future.

> - on Windows there's a question-mark icon which should lead to some help text. Did you intend to have some help, or should that icon be removed?

I'll try to remove it for v0.95. But in general, this leads me to the question if we want to include a Help to the software -> #269

> - what should it do if you multiply it horizontally to more than 200 pixels wide? Currently it overflows the display in a weird way. But just chopping it at 200 might not be the right solution because there is also the ability to re-center it, what does anyone else think? Or maybe it's OK, users will learn not to multiply it much past 200.

We could limit the multiplier to ceil(200/patternWidth). So it is possible to multiply until you are exceeding 200 needles, but can't enter completely random values.
-> #270

**Comment by Adrienne200** [comment]
The ? is gone from Windows now, thanks.  For the rest of the comments, yes let's go with it as it is and see what people think.
