### ISSUE TITLE
Sometimes doesn't beep immediately when moving to the left

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#154]
This is when knitting a fairly narrow piece, so you don't need to cross the turn marks after the first row. 
Sometimes, when coming off the knitting at the left end, the beep doesn’t sound immediately. Do not turn around. Stop the carriage and wait a few seconds, nothing happens. Continue moving the carriage another couple of centimetres to the left, sometimes it takes doing that a second or third time, then the beeper sounds and all is well, you can now turn around and knit back left->right. 
If necessary, go out to the turn mark, that will always work to cause the beep to sound. This may happen several times consecutively, then not happen again for a long time.

**Comment by chris007de** [comment]
There is room for improvement of the position where the shield recognizes that the carriage has left the pattern. Currently, it's set pretty conservative because we wanted to avoid to have people moving the carriage in the reverse direction too early, just because they hear the beep, but did not leave the knitting area yet. But it might be too conservative, especially on the left side.
I guess this needs some testing with different values.

**Comment by chris007de** [comment]
This issue was moved to AllYarnsAreBeautiful/ayab-firmware#9
