### ISSUE TITLE
Documentation of deployment for Mac

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#158]
AYAB v0.8 was fortunately built by a community member, but we still do not have any documentation on how to do this on our own for future releases.
We have to find someone who can do and document the deployment of the software on a Mac system.

**Comment by chris007de** [comment]
The v0.8 release was done by twitter.com/chs_sch, perhaps we could ask him (again) for a step-by-step recipe for deployment

**Comment by oskay** [comment]
Has someone reached out to chs_sch yet?

**Comment by chris007de** [comment]
I just sent him a PM on Twitter, let's see :+1:

**Comment by chssch** [comment]
Hey, I'll try to have a look into this and try to recall what I did the last time. Just to get started, do you use any other libraries / Qt versions since v0.8?

**Comment by oskay** [comment]
While I don't know the answer to that question (hopefully @chris007de will weigh in), and I don't want to get too far ahead of where we're at, I would note that it would be beneficial to include the following things into future builds, if/when possible:

* avrdude (for flashing firmware, #157) 
* libtiff
* qt

I do not know what exactly is involved in building each of these elements in. However the current version requires packages installed through homebrew, which is more work for the end user than is ideal. (I can provide assistance with some of these parts including testing, avrdude tweaking, and helping out with builds, once I have a recipe.)

**Comment by chssch** [comment]
Qt is probably difficult to bundle within the app, but maybe we can try. I started with the documentation process (It's not working yet though, still get some libs dependency errors).

Since I don't have time to get further into this in the next days, here is where I got so far:
https://gist.github.com/chssch/97ad196612e176f9e15773af02697c26

**Comment by chris007de** [comment]
@chssch 
> Just to get started, do you use any other libraries / Qt versions since v0.8?

Nope, no new libraries added since 0.8 so far.

**Comment by bamundy** [comment]
Hello,

I have a MacBook Pro with MacOS 10.12.1 and a Brother Electroknit KH-940 and the EMSL AYAB interface for 930/940 installed.

I have downloaded and installed the AYAB for Mac software according to the documentation found online at http://ayab-knitting.com/shield-software/    installing xcode, homebrew, Qt 4.8, and libtiff. I have downloaded the DMG and installed AYAB in my applications folder.

When I attempt to open AYAB, it "bounces once" and goes away . . . .

When I attempt to run the script in terminal I get an error code
- Last login: Mon Dec 26 20:39:44 on console
- Bs-MacBook-Pro:~ bjam$ python ayab_commandline.py pattern.png
- python: can't open file 'ayab_commandline.py': [Errno 2] No such file or directory
- Bs-MacBook-Pro:~ bjam$ python ayab_commandline.py eracce logo.png
- python: can't open file 'ayab_commandline.py': [Errno 2] No such file or directory


I really want this to work . . . what do I do next . . . 

Jo Ann

**Comment by oskay** [comment]
Hi Bamundy,
While your issue _is_ important, it is not categorized correctly, as it is not actually part of this "Documentation of deployment for Mac" discussion-- that's about how to build the AYAB Mac application from the source code. 

I'll give you (what I think is) the answer here, however, if you do have continued trouble, _please do not respond in this thread_ but I'll ask that you instead kindly create a new issue to describe the issue, where it's appropriate for us to follow up and help you there.

When you try to open the AYAB software for the first time, either right-click on the icon or control-click (not command but control) on the icon, and select "Open" from the pop-up menu. That should give you a dialog box to confirm that you do want it to open.  (Thanks, and sorry to be fussy about categorization.)

**Comment by oskay** [comment]
I have spent a couple of long days working at this (and trying to get it to work on QT5, since downgrading to QT4 and especially its dependencies broke much of the other software that I use) but haven't run into any kind of access control issues that look like SIP. I have run into hundreds of other errors that I have managed to get through, and finally come across one of these "Operation not permitted" errors, but the chain of errors started here:

`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: '/Users/oskay/Documents/Development/Qt/5.7/clang_64/plugins/imageformats/libqdds.dylib.dSYM/Contents/Info.plist': The file was not recognized as a valid object file.
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool: internal objdump command failed`

(That file does exist and appears to be valid.)

I think that I'm giving up here. This kind of application building is way outside of what I know how to do well.

**Comment by oskay** [comment]
As a separate note, there are a number of other ways to get a python app bundled into a stand-alone app on the Mac. If there is a way to get the app running from source on the Mac, that would be a great start. @chssch are you able to run from source?

**Comment by chssch** [comment]
hey @oskay yeah, running it from source was no problem (at least the ui shows up, cant test more since i dont't have anything like a knitting machine):

I use python ayab_devel_launch.py

![image](https://cloud.githubusercontent.com/assets/438695/21984293/907be374-dbf5-11e6-8147-8ffc8b501b29.png)

This should already work after installing pyqt4 stuff and setting the PYTONPATH env right. Have you fully migrated to QT5 already? If you push it to a branch somewhere, i can check it out and test.

**Comment by oskay** [comment]
I was able to write a launcher of my own to launch it-- I didn't see ayab_devel_launch.py, and mine apparently does the same thing. :P 

However, I apparently can't run from source without a segmentation fault that occurs when importing some of the QT4 libraries. (It's probably an installation problem with *something* -- but I spent two full long days fighting this and some related issues, installing and uninstalling all of the relevant packages many, many times, in many, many different ways. I cannot afford to spend longer on this.)

I have made some progress on the QT5 port, but I am stuck at how to migrate the signals. (On first examination, this may be beyond my skill.) The signal and slot methods that are used in ayab were deprecated as of a late QT4 version, and are missing entirely from QT5. They are replaced with "new style" signals and slots that are supported in both QT4 and QT5. If it were possible that you (or someone else) could migrate the signals and slots to the new syntax on a working QT4 installation, I could pick up from there and see how much further I could get on the QT5 port.

Documentation is here:

http://pyqt.sourceforge.net/Docs/PyQt5/pyqt4_differences.html#old-style-signals-and-slots
http://pyqt.sourceforge.net/Docs/PyQt4/new_style_signals_slots.html
http://pyqt.sourceforge.net/Docs/PyQt5/signals_slots.html

**Comment by oskay** [comment]
Now that the we're up and running (Mac included) on QT5, it would be worth revisiting this, to see if things drop into place a little more easily now.

**Comment by chris007de** [comment]
@derchrisuk is working hard on it...still problems with getting the dmg (.app) to load AYAB correctly. Launching the file in the container seems to work.

**Comment by derchrisuk** [comment]
I think we can close this.
A working App has been implemented, just ironing out some bugs.

**Comment by bamundy** [comment]
How do I get this app for the Mac I cannot get my evil mad scientist board to work at all… So is far as I'm concerned but all your answer beautiful app is not working

Forward together,

jam

**Comment by oskay** [comment]
@bamundy This is not an appropriate place to request help with that. Please contact Evil Mad Scientist  technical support directly.

**Comment by chris007de** [comment]
Let's close this and discuss detailed issues in separate entries
