### ISSUE TITLE
Extra needles selected on a long piece if you don’t cross the turn marks

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#161]
Mispatterning happens when knitting a long narrow single-bed piece for some time without ever crossing the turn marks.  (See below for recently-spotted similar behavior using the lace carriage.)

 - seen on both AYAB and EMSL hardware:
   - Preassembled shield bought from Tinkersoup in January 2015.
   - Early production EMSL board
 - Brother 910
 - 0.8 firmware on Mac, also 0.75 and 0.8 Windows
 - the attached Guild Banner 2.png file.  66 pixels wide and 711 long.
 - single bed 2-color, center. (doesn’t happen using double-bed, because you pass the turn mark)
 - 66 needles in work. L33-R33.

You can use actual yarn, or just “air-knit”. If you are air-knitting, it is useful to mark the bed with the two places where most needle-selection happens in this design; L4-R16 (the lettering) and L18-L24 (the needle design). Apart from one obvious area of the design around lines 308-329, there should never be anything selected outside of L4-R16 and L18-L24.

Start knitting as usual at the beginning of the design, note that there are some white-only lines first.
IMPORTANT: to see these bugs do not let the magnet go outside the turn marks, this is a narrow design and there is plenty of space to wait for the beep and turn around without crossing the turn marks on either end.

Two bugs to look out for.
 **Bug 1**: I logged this already as #154, that it sometimes doesn’t beep immediately on the left.
 **Bug 2**: (see pictures) After some time of knitting without ever passing the turn marks, (somewhere between 100 and 200 rows) it will suddenly start selecting extra needles, usually during the right->left rows only. I’ve included two sets of photos/screenshots for 2 of the 4 or 5 times it happened in this run-through. First batch was at row 158 and for a few rows after that, until I reset it by crossing a turn mark. Row 158 is in the letter “i” of Knitters, so it should be 2-black, one white, 17 black.  The green lines in photo IMG_7987_row_158 are correct, the reds should be back at B position.

This will happen again on the next right-left row, and the next. It sometimes stops again on its own, but I found that the most reliable way to cure it is to pass the left turn mark. That zeroes everything out and it restarts its positioning calculations from the beginning.  Then it’ll happen again in a while if you don’t cross a turn mark sometimes.

 It happened again this run at rows 264, 258, 271 and 488. The second set of sample data is from row 488, in the letter “a” of San Francisco. What usually happens is that it selects an extra copy of the real design, shifted 16 needles to the left. In IMG_8009_row488.JPG, my finger is pointing at the incorrect selection, the other two selected groups are correct.

**Probably the same thing, with lace:**
For this you need a lace carriage; typically the problem happens within 30-50 rows, no need to knit hundred of rows. The needle selection for lace should work exactly the same, I have no idea why this shows up sooner with the lace carriage.
Tips for using the lace carriage:
 - never let it select two needles forwards side by side, it MUST be only single needle patterns. The carriage will jam on the next row if 2 needles are selected together. Only use patterns designed for lace.
 - to actually knit from the sample lace pattern, you need to Mirror the image. That is, put it back to the way Brother designed it; for lace the automatic mirroring is not what you want. Not needed if you are just air-knitting to see this issue. Also to actually knit this, be sure the F/L switch on the lace carriage is at L.

Use the pattern “910 lace 10-35 60x30.png” basic settings as usual, 2-color, start form row 0, start/stop=30, Infinite Repeat, Single, center.
Knit as usual, except using the lace carriage instead of the K carriage. If air-knitting, no need to use the K-carriage at all.
Keep knitting, waiting for the beep every row as usual. it’s OK to cross the left turn mark sometimes, it will still fail anyway.
Notice that the pattern is regular, every row has only one needle selected per repeat, 10 needles apart.
Watch the selection, the every-10th pattern is consistent, until after 30 - 50 rows suddenly one row it’s different. It has selected some extra needles. They are regular, usually 4 needles offset from the actual pattern.
[Lace.zip](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/654046/Lace.zip)
[AYAB mispatterning.zip](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/654047/AYAB.mispatterning.zip)

**Comment by chris007de** [comment]
We've experienced such a behavior also during some marathon-knitting sessions on maker faires etc.
By evaluation the log files, we could see that the software side is obviously sending the correct data for each line to the Arduino, but still, it begins to make errors after some time.
We identified it as a problem of keeping track of the belt phase shift.

In case you are not familiar with the belt phase shift:
As you know, at the beginning of each knitting, you have to "initialize" the machine.
This is done by passing the carriage past the left hall sensor. By doing this, the Arduino can recognize the point of origin (leftmost needle) and, the belt phase shift. To know the belt phase shift is pretty important, as the carriage has two different possibilities to catch the belt when putting the carriage into one of the K modes. If the belt phase is not recognized correctly, a offset of 4 needles is the result.
Sadly, it is only possible to reliably recognize the belt shift in front of the left hall sensor, this is by design of the knitting machine hardware.

So our assumption is:
When knitting a long piece, little (mechanical) inaccuracies accumulate to a bigger and bigger error, until the phase shift is not correct anymore and the needles are getting set in the wrong manner.
This can reliably (?) be avoided by passing the hall sensor from time to time.
As a "workaround" we also thought of showing an indication in the software to do so every 100 lines or so.

To fix the root cause of this problem, we have to understand where this accumulating error comes from and whether it is even possible to even it out across models and single devices.

**Comment by Adrienne200** [comment]
I knew about the belt phase, but not that it is only reset by the left Hall sensor. 
I thought that my main test was getting offsets of 16 not 4, but the cause could still be the same. 
Did you try my second test, with the lace carriage? That failed much sooner, sometimes in as few as 8 rows after crossing the left turn mark. And always with an offset of 4, which fits with your theory about the belt phase.

**Comment by oskay** [comment]
Given that the physical belt position does not change, it is hard for me to imagine that a mechanical inaccuracy could lead to a full belt phase change. It should be possible to display the current needle and phase in debugging outputs to track this down.

**Comment by oskay** [comment]
This issue seems to keep coming up, and I think that it should be prioritized. What can we do to track this down?

**Comment by chris007de** [comment]
Reading the error description by @Adrienne200 and combining it with our own experiences, I still think that it is some kind of "loss of orientation" during long knitting streaks without re-calibration of the origin.
Here comes some speculation:
- Perhaps this bug also occurs on machines without AYAB? Perhaps until now, nobody every knitted patterns of >250 lines and more in a single streak with a genuine machine, as it was simply not really feasible or convenient to do so with Mylar sheets.
- What we were also experiencing is that we had the impression that the solenoids are tending to run "hot" over a long streak of knitting a pattern. When we were knitting >500 lines on Maker Faires or similar, just turning off the PSU for 15 minutes often solved some mispatterning also.

What can we do about this?
- Explain the people that they are using hardware which is about 30 years old and what to expect from this (fun and experience) and what not (perfectly working system in each and every condition), but we are working constantly on improvements.
- Constantly tracking and logging carriage position and belt phase information to be able to correlate misbehavior with sensor data
- Hot fix: Tell people to pass the sensor from time to time, or even implement an active request telling the user to do some every 100 lines or so in the GUI.

**Comment by Adrienne200** [comment]
No, IMO we need to keep working on this, AYAB is not a fully useable product while it still has this mispatterning. Selection errors basically never happen in Brother native mode, unless there’s an individual mechanical or electronic failure, or dirt on a mylar. Remarkably, Brother patterning mechanisms were essentially 100% reliable, including some very heavy use. I have never heard reports of mispatterning anywhere else but AYAB. 
You could totally make a long scarf using the mylars, and people did/do. The mylar rolls automatically back to the beginning after up to 150 rows and repeats the pattern. And don’t forget that the later models never had mylars, they were fully electronic.  

I like the idea of a logging/debug mode, might give us some clues as to what’s going wrong. Though aren't we mostly in the firmware here, how much logging can it do?

If solenoids are running warm that should be looked at anyway, but this issue is fixed by crossing the turn marks and continuing to knit, so it seems unlikely to be caused by overheated solenoids. I haven’t studied the code in detail, but I did notice a fail-safe where power is removed from a solenoid if it has been engaged for too long. Maybe shorten that time? And log when that call is made, see if it is invoked often.

If there’s no other short-term solution then yes, it could count how many rows it has done since last crossing a turn mark and prompt the user. Ugly but effective.

Then there’s lace. Have you tried the second half of this case, with the lace carriage? I probably should have logged that separately, it could be a different bug. Typically fails sooner. And for lace you are crossing the turn marks often. Does the lace carriage get different timing?

**Comment by chris007de** [comment]
> No, IMO we need to keep working on this, AYAB is not a fully useable product while it still has this mispatterning. Selection errors basically never happen in Brother native mode, unless there’s an individual mechanical or electronic failure, or dirt on a mylar. Remarkably, Brother patterning mechanisms are essentially 100% reliable, including some very heavy use. I have never heard reports of mispatterning anywhere else but AYAB.
You could totally make a long scarf using the mylars, and people did/do. The mylar rolls automatically back to the beginning after up to 150 rows and repeats the pattern. And don’t forget that the later models never had mylars, they were fully electronic.

Ok, good to be sure that "Brother native mode" does not have such problems. I just wanted to avoid that we pursue a behavior which the original setup was not able to achieve anyway.

> I like the idea of a logging/debug mode, might give us some clues as to what’s going wrong. Though aren't we mostly in the firmware here, how much logging can it do?

See https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/257

> If solenoids are running warm that should be looked at anyway, but this issue is fixed by crossing the turn marks and continuing to knit, so it seems unlikely to be caused by overheated solenoids. I haven’t studied the code in detail, but I did notice a fail-safe where power is removed from a solenoid if it has been engaged for too long. Maybe shorten that time? And log when that call is made, see if it is invoked often.

The only situations where needles are reset are when the carriage is out of the active needle range (https://github.com/AllYarnsAreBeautiful/ayab-firmware/blob/master/knitter.cpp#L249) or when knitting is finished (https://github.com/AllYarnsAreBeautiful/ayab-firmware/blob/master/knitter.cpp#L263).
There is no fail-safe/timer which avoids continuous operation in the firmware.

> If there’s no other short-term solution then yes, it could count how many rows it has done since last crossing a turn mark and prompt the user. Ugly but effective.

I would definitely implement this anyway, as we could get this nearly for free as soon as we have done https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/257

> Then there’s lace. Have you tried the second half of this case, with the lace carriage? I probably should have logged that separately, it could be a different bug. Typically fails sooner. And for lace you are crossing the turn marks often. Does the lace carriage get different timing?

The decision which pixel has to be taken for setting the needle is slightly different for the L carriage (https://github.com/AllYarnsAreBeautiful/ayab-firmware/blob/master/knitter.cpp#L315 and https://github.com/AllYarnsAreBeautiful/ayab-firmware/blob/master/knitter.cpp#L340, depending on the direction of the carriage) because it has a different mechanical length than the K carriage. These values were found empirically and therefore might be not perfect.
But in terms of timing for recognition of the current carriage position, it's the same as for the K carriage.
If you have the feeling that it might be a separate issue, please split it out into an additional entry.

**Comment by t0mpr1c3** [comment]
I'm not saying this is not an important issue, but from what is recorded above it seems this is not an issue for the desktop software. It is a firmware or possibly even a hardware issue, and should be raised elsewhere.

**Comment by dl1com** [comment]
> This was resolved in [ayab-firmware#48](https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/48)- can we close this now?

agreed.
