### ISSUE TITLE
Update QT signal & slot with non-deprecated syntax

### ISSUE THREAD

**Issue by oskay** [AllYarnsAreBeautiful/ayab-desktop#171]
The signal and slot methods that are used in ayab were deprecated as of a late QT4 version, and are missing entirely from QT5. They are replaced with "new style" signals and slots that are supported in both QT4 and QT5. If someone could manage the process of migrating the signals and slots to the new syntax on a working QT4 installation, it should not break anything, yet would be extremely helpful in easing our transition from QT4 to QT5. 

(QT 4 is no longer supported. Migrating to QT5 would ease future development on a number of fronts, including at least issues #158, #166, and #169.)

Documentation about the syntaxes is here:

http://pyqt.sourceforge.net/Docs/PyQt5/pyqt4_differences.html#old-style-signals-and-slots
http://pyqt.sourceforge.net/Docs/PyQt4/new_style_signals_slots.html
http://pyqt.sourceforge.net/Docs/PyQt5/signals_slots.html

**Comment by chris007de** [comment]
I just had a look and changed the signal/slot syntax to be compatible with PyQt5: 89c20fc

Migration is not finished with this commit, as the module PyQt4.QtGui was split into three separate modules PyQt5.QtGui, QtWidgets and QtPrintSupport. We have to check where we have to use QtWidgets instead of QtGui in the whole source.
So there is still some migration and testing to be done to be fully operable with PyQt5, but should be doable in a decent amount of time.
Contribution on the pyqt5 branch is appreciated!

**Comment by oskay** [comment]
Fantastic-- thank you. 

I've made some progress on the other parts of the migration already (including the QtWidgets thing), and I'll try to make another stab at it with this update.

**Comment by oskay** [comment]
Adding link to this branch: https://github.com/AllYarnsAreBeautiful/ayab-desktop/tree/pyqt5

**Comment by oskay** [comment]
Marking this part of migration as complete.
