### ISSUE TITLE
talk to valentina about our project

### ISSUE THREAD

**Issue by niccokunzmann** [AllYarnsAreBeautiful/ayab-desktop#18]
This should make clear, how to use their software to create sewing patterns for our software

**Comment by kirstin** [comment]
We have talked and have come to the following conclusions:
  - we will not use the valentina -format directly
  - we want to use the SVGs which Valentina can generate for patterns
  - Patterns should be specifically designed for knitting
  - specifying the grain line is important, in order to know where knitting begins and ends
  - SVGs are powerful and awesome
