### ISSUE TITLE
Problem with 200 px wide image

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#184]
I opened a file that’s 200 sts wide, it opened as 100x100 as expected. But then when I changed one side to 90 then 70, it displaced the image, see screenshot. Again, can’t swear that it wasn’t like this before. It would probably knit it correctly, but the display is wrong.

https://files.gitter.im/AllYarnsAreBeautiful/Lobby/xRwz/AYAB0-9RC1pattern-shift.PNG

(reported by @Adrienne200)

**Comment by chris007de** [comment]
@Adrienne200 I can't see exactly what goes wrong, could you please describe a bit clearer?

**Comment by chris007de** [comment]
@adrienne200
Do I remember correctly that this issue was not really an issue?

**Comment by Adrienne200** [comment]
Yes, I think this was operator error, you can close it.
 With an image that's 200 pixels wide, when you start changing the numbers for the start/stop needles to say L50 and R30, the image displays oddly, displaced off to one side. But it's because it is also keeping to the Center Alignment, I think it's doing the right thing.
