### ISSUE TITLE
Mac: Load Image should not default to the Resources folder

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#211]
0.9RC8
After launch, the first time you click Load Image File, it opens to:
Windows C:\AYAB   This is fine, good enough, the patterns folder is right there as a next step.
Mac: Applications/AYAB-Launcher.app/Contents/Resources/  This folder is buried inside the app package where normal users never go.  Not so good, we want to steer them towards Documents/AYAB which contains the copy of the Patterns folder.

In both Mac and Windows it correctly remembers your last image location and goes there next time during the session.

**Comment by derchrisuk** [comment]
I have a solution to propose.
On the first start it will default to the users home folder.
Once a file has been loaded, it will use the same folder again if you try to open a new file.
This will affect all OS we have builds for.
Additionally, I would also change the location of these patterns.
Create a AYAB folder directly in the home folder.
Because the way we do it currently it is possible that if a non English OS is opening the app that it might fail, because of the localised folder structure.
But home folder is always the same, in a programmatically way.

**Comment by oskay** [comment]
I agree that defaulting to the user's home folder for opening files is best practice. 

I am not sure that creating an AYAB folder by default in the home directory is a good idea-- it can be a bit cluttering, and the end user may or may not be aware that they can move it to other places. So, it would be nice if there were a way to automatically create that in Documents instead. However, I'm not immediately aware of any language-independent way to do that.

One approach would be to do something like (in pseudocode):
```
try:
    Create AYAB directory in ~/Documents/
except:
    Create AYAB directory in ~/   # Backup plan
```

Another approach would be to make a menu item for install example patterns, that would prompt the user for an installation location.

**Comment by derchrisuk** [comment]
There is a python library which we could use for that.
Will have a look.

**Comment by derchrisuk** [comment]
This should be fixed with the next RC.
For now the file dialog will default to $home on first start, or last file location

**Comment by Adrienne200** [comment]
0.9RC10. 
Load Image on both Mac and Windows now opens to their home folder.
Will the Patterns folder be copied somewhere automatically? Or it could just be a step in the install instructions.

**Comment by derchrisuk** [comment]
For now we will include the default location for Mac, Windows and Linux in the documentation.
The only copy is happening on Mac because of the source location within the App bundle, which you are not able to browse to that easy as a normal user.
A goal for a next release could be to centralise the file locations.

**Comment by Adrienne200** [comment]
I agree, this is good enough for now, revisit next release.
