### ISSUE TITLE
Sign Windows executable

### ISSUE THREAD

**Issue by dl1com** [AllYarnsAreBeautiful/ayab-desktop#218]
To avoid warnings when opening ayab.exe, sign the binary.

**Comment by t0mpr1c3** [comment]
Authenticode certificates start at about $200 for 3 years (e.g. https://comodosslstore.com/codesigning.aspx). For this price, SmartScreen will tell users that their untrusted executable comes from "AYAB" instead of "unknown publisher". It will still get flagged because our user base is small and too few people will install the software for the certificate to gain any significant reputation.

Too expensive, in my view. I would rather buy the AYAB development team lots of beer. :)

(As an aside: I hope to visit Germany next year because my sister will be taking an internship in Berlin, so perhaps the beer thing is not entirely out of the question.)
