### ISSUE TITLE
Pixels shown on screen should match the selected needles on the machine bed

### ISSUE THREAD

**Issue by still-optimistic** [AllYarnsAreBeautiful/ayab-desktop#229]
The main AYAB window shows the orange and green sides so they match the machine - great.  But the portion of the image shown on the orange side is actually knit using the green needles.  This is presumably expected because we're looking at the reverse side of the fabric as it is knit.  

However, it would be better to flip the image horizontally when displaying it in the main window.  This means that it would not directly match the input png, but also that the row of pixels displayed on the screen will match the actual needle selection on the machine bed.  This would be super useful for quickly detecting mis-selected needles.  At the moment, because the screen does not match the needles on the bed, I have to flip each row horizontally in my head (I am too impatient to actually do this carefully, so I screw it up a lot).

**Comment by chris007de** [comment]
That's actually a very good point, we will fix this in the next version

**Comment by chris007de** [comment]
I just wanted to implement the change, but then I hesitated because I want to avoid that users get confused because they do not know when they see the front- or the backside of the knitting.
So I propose to leave the pattern representation as it currently is, so people see what the outcome will look like.
When starting to knit, we mirror the representation so they see what the backside of the knitting looks like and to help debugging of mis-selected needles. When knitting is finished or cancelled, we switch back to original representation.
@Adrienne200 @still-optimistic what do you think about this approach?

**Comment by oskay** [comment]
Make sure and label it clearly whether it's the forward or reverse view.  A useful tool would be to have an image that is shown forward and backwards in the two contexts-- maybe a PNG of "AYAB" that clearly shows backwards when in reverse view.

**Comment by Adrienne200** [comment]
I’m not sure either what the right solution is for this question. It's an interesting idea to flip the display just while actually knitting, yes, I think I like that.

Or maybe the real question is, is it actually desirable to always mirror the image? Brother did not; the knitting on the machine normally matched the chart as you looked at it, even though for some patterns that means it is backwards. If you needed it for lettering or a photo or whatever you used their Reverse button, or you designed it backwards in the first place. Using their reverse button, the effect was the same as AYAB is now, the left side of your chart was knitting on the right needles, and vv.  The charts in the back of the Stitchworld book (the built-in patterns in the 930 and later) are all shown as you view them while knitting. The photos of the finished samples in the front of the book are the other way around.

AYAB’s automatic mirroring is annoying for lace. All Brother lace patterns are designed to be used as they are; if you accidentally knit them mirrored at least they will not look right, and at worst it can cause carriage jams because it’s trying to move stitches in the wrong direction. Of course it’s possible to do the mirroring before you save the image, but then you have to keep track of which is which, and it’s hard to tell with lace patterns by just looking at them. I’d prefer to keep them all as designed, which currently means remembering to (un)mirror each one as I open it to knit.

One possible solution is a Preference setting (#238). If I’m doing a lace project, I’d turn off the automatic mirroring, if I mostly work with photos or lettering I’d want it on. Or there’s the checkbox I suggested in #236, that might be the easiest interim solution to make this more smooth while we ask the community what they think. I also like Windell’s idea of an AYAB graphic forwards or backwards, which can be combined with these other ideas.

**Comment by t0mpr1c3** [comment]
Not sure what the current status of this is, but personally I favour a preference setting that defaults to no mirroring.

**Comment by chris007de** [comment]
Status is unchanged. As solving this issue requires a solution for storing preferences, going for #238 first might be worthwhile.
