### ISSUE TITLE
Needles outside the start/end range get the contrast color when knitting DBJ

### ISSUE THREAD

**Issue by still-optimistic** [AllYarnsAreBeautiful/ayab-desktop#231]
I knit a 50 needle pattern (25-orange to 25-green) in double bed jacquard, and added an extra needle on the main bed because my instructions said it needed to be an odd number of needles.  I found to my surprise that the extra needle was knit as the contrast color rather than the background color.

I'm guessing I should have changed the stop needle to 26 green... but it appeared that the software properly managed the needle, always selecting it for passes with the contrast color, and never for the bg color.

**Comment by chris007de** [comment]
Just making sure I understand your post correctly:
Needles which are inside the specified knitting range but outside the loaded image should be knit in background color rather than contrast color?

**Comment by still-optimistic** [comment]
I meant needles outside the specified knitting range should be knit in the background color.  In thinking about this, I realized I am entirely unsure how needles outside the specified range are handled.  But I would expect that the image/pattern would be ignored outside the range, and needles would be knit using the background color.  So, the knitting range could be adjusted to knit only a portion of the image.  However it works, though, it seems like picking the contrast color is the wrong thing, and that is what I observed.  I'm also not sure if this bug occurs with all pattern knitting, or only when the machine type is set to ribber.

**Comment by chris007de** [comment]
The knitting range has to set correctly in order to set the needles properly. Without a correctly set knitting range, the system does not know when the current line is finished (and therefore, not when to do the beep and the transmission of the next line). So it has to be set correctly, reflecting the range of needles actually set into active position on the machine by the user. This is applicable to all three cases (knitting range bigger, smaller or equal the actual image width).
So knitting outside the specified knitting range is the user's fault in the first place.
But to catch this misuse gracefully, we can set the needles to background color in DBJ, that's no big issue.

**Comment by still-optimistic** [comment]
Yeah, that is sort of what I figured.  But I am glad we can handle this gracefully.

**Comment by chris007de** [comment]
> But to catch this misuse gracefully, we can set the needles to background color in DBJ, that's no big issue.

@t0mpr1c3 Just to be sure, was this solved by #348/#349?

**Comment by t0mpr1c3** [comment]
I think so, but I will have to check.

**Comment by Adrienne200** [comment]
This is partially fixed. Flanking needles in 2-color DBJ are knitted in white as expected in all modes. For 3 or more colors, Middle-twice looks correct now, but not Classic or HoP. I'm closing this and logging #690 to describe the current behavior.
