### ISSUE TITLE
Easier cross platform installations

### ISSUE THREAD

**Issue by Sturla22** [AllYarnsAreBeautiful/ayab-desktop#253]
Hi!
I just ran into [this repo](https://github.com/mherrmann/fbs) today and thought you might be interested in it.
According to the documentation it should enable easier cross platform installations, I for one had problems with generating an executable for windows when working on my pull request for the ayab-desktop.

All the best,
Sturla

**Comment by chris007de** [comment]
Thank you very much for the info, let's try this when the next release comes up.

**Comment by chris007de** [comment]
Some words on the current state of work:
I tried fbs on the branch https://github.com/AllYarnsAreBeautiful/ayab-desktop/tree/v0.95_fbs. For Linux, it looks pretty promising. I did not test it on Windows or even Mac, but that are the next steps.

But before, there are some drawbacks I stumbled upon:
* fbs builds its own "AppContext" around the application, which is nice because we do not really have to care about different filepaths when runnning in development or deployment. But it requires that you run the app with `python3 -m fbs run`. I am not sure how this will be compatible to the PyPi setup flow. But in  the worst case, I would say we can life without PyPi and distribute a tar/zip file with a precompiled binary. For development, cloning the git repo and running it in a venv will stay the way to go, just as it is today.
* We use yapsy as library to realize a plugin management because at the very beginning of the AYAB software we thought of adding plugins for Pfaff etc. in the future.
But, yapsy expects the plugins to be in a certain structure in the file system (yapsy-plugin file lies next to the plugin package folder). fbs uses PyInstaller pack the compiled python for distribution. The folder structure is not preserved, which causes yapsy to stop working.
There is a workaround for this (manually adding the plugin folder structure as resource files), but I would say this is not how this whole thing is intended to work. (Fun fact: as we are currently also deploying with PyInstaller, we are doing exactly the same thing).
If nobody finds a solution how to marry PyInstaller and yapsy in a convenient way, I would say we get rid of yapsy, as there will probably never be another plugin for the AYAB software. If there will be additional functionality for another machine manufacturer, we will surely find a way to include it without a plugin library.

If somebody got comments on the topics above, please tell :)
@Sturla22  @oskay

**Comment by chris007de** [comment]
Update:
AYAB is running on Win10 and macOS 10.14. Building an Windows installer and macOS DMG file works fine.
Now I have to adapt our build scripts to do this also automatically, then we should be ready to go :)

**Comment by chris007de** [comment]
@Adrienne200 @oskay Any comments on this? Is post61 running on Win7, Win10 and macOS (>= Sierra)

**Comment by oskay** [comment]
Im not sure what "post61" is.

**Comment by Adrienne200** [comment]
Post 61 is the build number from the build that Chris sent by email on Nov 18th.

**Comment by chris007de** [comment]
No negative comments here for a while, so I guess it's ok. -> closing
