### ISSUE TITLE
Multicolor *.png

### ISSUE THREAD

**Issue by Ilushock** [AllYarnsAreBeautiful/ayab-desktop#297]
When I upload a multicolor (more than 2 colors, not a black&white) picture to AYAB, it changes my colors to other. What colors should I use in my pattern to make AYAB do not any changes?
My pattern:
![Квадраты24х48_СЗ_образец](https://user-images.githubusercontent.com/34733861/74440605-b60bce80-4e87-11ea-9c82-277001f6e18b.png)
After uploding into AYAB:
![screen](https://user-images.githubusercontent.com/34733861/74440700-efdcd500-4e87-11ea-9dee-5a209fb67934.png)
It is also unclear in what order of colors the software begins to push the needles when knitting. I think that it would be much clearer to indicate not ABCD-colors when changing the color, but those colors (on-screen) that the program recognized in the uploaded pattern.

**Comment by chris007de** [comment]
Currently, only grey-scale multicolor images are officially supported. (the 256 bit range for a pixel is divided by the amount of chosen colors and mapped to the colors accordingly).
E.g. For 4 colors -> A: 0...63, B 64...127, C 128...195, D 196...255

This is simply due to the lack of a concept for handling colored multicolor images.
If there are really only 4 colors in the png, we could simply map them to the colors ABCD and show them. When a pattern is created manually, this should be the case.
But people might also load a photo with a vast amout of colors into the software. How to decide which are the 4 colors we rely on? Should we quantize down to 4 colors automatically (which alters the photo and might not be what the user is expecting)?
For now, we could just throw an error message that the image has more than 4 distinct colors...

Why your picture is shown with wrong colors in the GUI is not clear to me yet, but I guess it's related to the color range we are using to open the image...I'll have look.

**Comment by Ilushock** [comment]
Gray-scale - it's OK. I'he understood, will try it.
About many colors... I don't think, that anyone, who use the AYAB, need this functions, There are many-many graphic editors. I think that people more or less understand the conception  will not upload patterns with more than 6 colors.
Thanks.

**Comment by t0mpr1c3** [comment]
Some kind of colour concept would seem necessary for display purposes if nothing else.

**Comment by t0mpr1c3** [comment]
So, Designaknit .STP files uploaded through the new code do seem to display in the correct colours, as far as I can tell.

**Comment by chris007de** [comment]
I guess the "false" colors behavior arises from https://github.com/AllYarnsAreBeautiful/ayab-desktop/blob/master/src/main/python/ayab/ayab.py#L245.

**Comment by t0mpr1c3** [comment]
By the looks of it this is an RGB versus BGR issue.

**Comment by t0mpr1c3** [comment]
I'm going to go ahead and label this issue "wontfix" until we know more. I think it is suspect an issue of the format of the image used as input rather than something internal to AYAB.

**Comment by chris007de** [comment]
Plus, it might be fixed by the the internal colour representation.
@Ilushock Close for now, please reopen if it still occurs in 1.0.0
