### ISSUE TITLE
Connection issue to KH910 [MacOS and Windows]

### ISSUE THREAD

**Issue by e-mln-e** [AllYarnsAreBeautiful/ayab-desktop#346]
I am encountering a connection issue with AYAB interface.
Past: everything was working fine some time ago with ayab desktop 0.9
Present: 

- Installed ayab desktop 0.95 and Silabs driver
- All goes as normal until I hit "Knit". The desktop interface indicates "connecting to the machine". The board green and orange leds flash. It never starts the knitting.
- Issue reproduced on a different Mac
- Issue reproduced with a virtual machine Windows 10

Logs (MacOS 10.14):
default 19:56:29.048127 -0700 AYAB Current system appearance, (HLTB: 1), (SLS: 0)
default 19:56:29.048793 -0700 AYAB Post-registration system appearance: (HLTB: 1)
default 19:56:29.370656 -0700 AYAB NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 1
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x600001bb2b70
 (
    "<NSAquaAppearance: 0x600002db3440>”,
    "<NSSystemAppearance: 0x600002db3200>”
)>
default 19:56:40.224384 -0700 AYAB WiFi Platform capabilities 38000.
default 19:56:40.224412 -0700 AYAB Device supports Legacy P2P
fault 19:56:40.291633 -0700 AYAB RETURNING UnknownFS PLACEHOLDER: <private>
fault 19:56:40.313039 -0700 AYAB RETURNING UnknownFS PLACEHOLDER: <private>
default 19:56:40.574491 -0700 AYAB SFBrowserCallBack (node = <SFNode 0x6000014a1700>{domain = Network})
default 19:56:40.586005 -0700 AYAB [WARNING] Failed to fetch all containers: Error Domain=BRCloudDocsErrorDomain Code=2 UserInfo={NSDescription=<private>}
default 19:56:50.171175 -0700 AYAB Connection to sharingd became invalid
default 19:56:50.306245 -0700 AYAB LSExceptions shared instance invalidated for timeout.
default 19:58:51.677018 -0700 AYAB OSErr AERemoveEventHandler(AEEventClass, AEEventID, AEEventHandlerUPP, Boolean)(aevt,quit handler=0x7fff30342497 isSys=NO) err=0/noErr
default 19:58:51.677057 -0700 AYAB OSErr AERemoveEventHandler(AEEventClass, AEEventID, AEEventHandlerUPP, Boolean)(GURL,GURL handler=0x7fff30342497 isSys=NO) err=0/noErr
default 19:58:54.900593 -0700 AYAB Current system appearance, (HLTB: 1), (SLS: 0)
default 19:58:54.901155 -0700 AYAB Post-registration system appearance: (HLTB: 1)
default 19:58:55.189960 -0700 AYAB NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 1
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x600003819e50
 (
    "<NSAquaAppearance: 0x600000e0a780>”,
    "<NSSystemAppearance: 0x600000e0a900>”
)>
default 19:58:58.281015 -0700 AYAB WiFi Platform capabilities 38000.
default 19:58:58.281044 -0700 AYAB Device supports Legacy P2P
fault 19:58:58.341894 -0700 AYAB RETURNING UnknownFS PLACEHOLDER: <private>
default 19:58:58.604721 -0700 AYAB SFBrowserCallBack (node = <SFNode 0x600003711480>{domain = Network})
default 19:58:58.608830 -0700 AYAB [WARNING] Failed to fetch all containers: Error Domain=BRCloudDocsErrorDomain Code=2 UserInfo={NSDescription=<private>}
default 19:59:04.330888 -0700 AYAB Connection to sharingd became invalid
default 19:59:08.376673 -0700 AYAB LSExceptions shared instance invalidated for timeout.

I tried everything I could think of (reinstall, reboot, etc), the board appears fine and properly connected. It might be related to a connection issue posted earlier?

**Comment by myronelliott** [comment]
Checking back in on this thread-- just got my system up and running, 24 hrs later I'm in this "Connecting to Machine" deathstare.  I've restarted machine, reloaded drivers, reloaded the AYAB software... still just "connecting to machine" .

**Comment by e-mln-e** [comment]
Afraid to say I haven't figured it out either!

**Comment by oskay** [comment]
It may potentially be helpful if both of you could provide some much more detailed information about the situation where this is occurring.  For example,

- Exactly which AYAB interface hardware you are using (please be as specific as you can)
- Exactly which OS version(s)
- Exactly which version of the AYAB software
- Any other potentially relevant configuration details
- Whether you have been able to connect to the AYAB interface otherwise (e.g., updating firmware, etc), indicating that the hardware is communicating to your computer.

Also, if ayab desktop 0.9 was working previously, it may well be best to try again with that version.

**Comment by myronelliott** [comment]
I'm more knitter than computer person, so I'll tell you what I know-- 
My board was fabricated by Wooly Logic Knits and purchased off Etsy this fall, and installed by a friend who was less intimidated than I.  

The software download I used is the most current one for Windows, v0.95, it was the only one I have ever used.  I am using the Arduino IDE drivers, which seem to be successful (have cleared and re-uploaded those to no avail).  I am running on a brand new laptop, Windows 10 Home.  

On the first day I was getting the machine connected, up and running (and figuring out casting on/etc because I've never been able to use this particular machine before, the original board was not functioning correctly) I got connected, and successfully knitted a few swatches and patterns, with the machine correctly selecting the patterns, I was able to knit a pattern that I had edited and configured myself as well.  I left the machine plugged in to the power source and computer.  The next day I came back to knit a real project, and the program cannot finish connecting/communicating with the machine, as described above, and just as above, the yellow light on the board does flash while it is "connecting to machine" but it never gets past that point.

I tried to connect with a different older laptop, same issue.  

I installed 9.0 (and python, I didn't have that before), rebooted, and it does not display the "connecting to machine" message, and the board does not flash when I hit the KNIT button.  Same end effect.  

I've ordered a new USB cord on the off chance this one is a dud, but the fact that I was up and running and then... kaput!  That's the part that stumps me the most.

**Comment by myronelliott** [comment]
I left as detailed a response as possible.  No luck with 9.0.  I've ordered
a new USB cord, due in tomorrow.  fingers crossed... but  not holding my
breath.

**Comment by e-mln-e** [comment]
Hi!
I dusted things off and re-installed ayab 0.9 - that did the trick.

However for documentation purposes:
- Evil Mad Scientist board for KH910
- Ayab 0.95 on Mac 10.14.6
- no other issue I can think of (I did check if I had the right version of the silabs driver)
- Firmware can be updated

**Comment by t0mpr1c3** [comment]
I'm glad that worked out for you!

Just for the record, we think that Myron's problem was the USB cord.

**Comment by spf173** [comment]
I'm having this same issue! The yellow light on the board flashes while it is "connecting to machine" but it never gets past that point.

I tried switching to 0.9 and I've tried ~10 different USB cables, but nothing has solved this for me quite yet. Current setup is:

- Wooly Logic Knits interface for KH910
- AYAB 0.95 on Mac 10.14.4
- When I try to flash firmware I get "programmer is not responding'" issue in log, but when I plug in the USB I hear the machine respond and I can select it in port selection

<img width="1012" alt="Screen Shot 2021-01-29 at 7 37 24 PM" src="https://user-images.githubusercontent.com/10519154/106342614-a2f83700-626f-11eb-8cc3-5544c7279d70.png">
