### ISSUE TITLE
Installation of `avrdude` needs to be part of the Linux documentation

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-desktop#371]
The firmware flash utility assumes that it is already installed, but it is not part of the build process.

**Comment by chris007de** [comment]
I do not quite understand the (intended) effect of your changes in #372
Avrdude is not part of the Linux package currently, as fbs is not configured to add the binary to the frozen application so the end user would have to install it on her/himself.
What was your intention?

**Comment by t0mpr1c3** [comment]
OK. So, currently the linux version does not recognize that `avrdude` is a dependency, it just raises a runtime error if it is not installed. I was trying to fix that, but I did not understand the build process. I'll close the PR but keep the issue.

**Comment by chris007de** [comment]
> OK. So, currently the linux version does not recognize that `avrdude` is a dependency, it just raises a runtime error if it is not installed.

Ok...we could probably show a notification to the user that the system lacks avrdude when the exception occurs?

> I was trying to fix that, but I did not understand the build process. I'll close the PR but keep the issue.

Well, for Windows and mac OS we are actually shipping the avrdude binary (see https://github.com/AllYarnsAreBeautiful/ayab-desktop/tree/85ca1a68e3d3a91b5cde3e95acf06dc73d1efe26/src/main/resources/base/ayab/firmware). Having these Windows and mac OS binaries in the repo is not desirable...but it's the status quo - I am open for ideas on how to improve this....for Linux we are not doing this because it is "easily available" through the packet manager of the OS.
Also, I don't know if it "one binary fits all" for Linux...will an avrdude binary run on each and every Linux distribution properly?

**Comment by t0mpr1c3** [comment]
> > OK. So, currently the linux version does not recognize that `avrdude` is a dependency, it just raises a runtime error if it is not installed.
> 
> Ok...we could probably show a notification to the user that the system lacks avrdude when the exception occurs?

That sounds fine.

> > I was trying to fix that, but I did not understand the build process. I'll close the PR but keep the issue.
> 
> Well, for Windows and mac OS we are actually shipping the avrdude binary (see https://github.com/AllYarnsAreBeautiful/ayab-desktop/tree/85ca1a68e3d3a91b5cde3e95acf06dc73d1efe26/src/main/resources/base/ayab/firmware). Having these Windows and mac OS binaries in the repo is not desirable...but it's the status quo - I am open for ideas on how to improve this....for Linux we are not doing this because it is "easily available" through the packet manager of the OS.
> Also, I don't know if it "one binary fits all" for Linux...will an avrdude binary run on each and every Linux distribution properly?

Good point. We probably don't want to get into making binaries for every flavour of Linux anyway.
