### ISSUE TITLE
Set up of application environment

### ISSUE THREAD

**Issue by dl1com** [AllYarnsAreBeautiful/ayab-desktop#375]
(Triggered by #371)

- To be able to run the software after cloning the repository and to properly generate frozen packages for Windows and macOS, some prerequisites have to be fulfilled.

  - [x] Generate the translation files. This can already be done with the `ayab_trans.pl` script.

  - [x] To be stringent, we may also require the Python ui files generated from the .ui files to be generated (e.g. ayab_about_gui.py from ayab_about_gui.ui), just as we do for the .qm files. As we already left the comfort zone of "clone the repo and run the software" by requiring the translation files to be generrated, this would not yield additional effort. A script is required to run `pyuic` on the .ui files. (to be discussed, @t0mpr1c3 ?)

  - [x]  We should download the avrdude binaries for Windows and macOS automatically from https://download.savannah.gnu.org/releases/avrdude/, unpack them and put them into the right place. (to be discussed, @t0mpr1c3 ?)

The three scripts for these actions could be called by a script (e.g. "setup_environment.sh").
Running this script after cloning the repository sets up a proper environment for running the application using `fbs run`.
Running this script would also be the foundation for running the existing build scripts (=generate Windows Setup and macOS application)
(for Linux we still have to finally decide how to distribute the software to non-developers/non-git users...tar.gz, pypi, AppImage,...?).

**Comment by t0mpr1c3** [comment]
Sounds good, Chris.

I don't have strong feelings about how to distribute the Linux. I guess I would go with AppImage, if it integrates easily into our pipeline? I would guess that tarballs might need to be versioned for different distros, and Pypi isn't going to reach many people who don't already use Git.

**Comment by t0mpr1c3** [comment]
I've written a script to generate Python files using `pyuic5`. It relies on the filenames having already been renamed, though, so I'll wait until after the renaming pull request is resolved before requesting the changes.

**Comment by t0mpr1c3** [comment]
I'm having a go at making a `build.yml` for the AppImage, which I'll put in branch `1.0.0-appimage`.

**Comment by t0mpr1c3** [comment]
This is what I've found out so far about building Linux apps:

1. `fbs` supports Ubuntu/Debian, Fedora, and Arch distros providing Docker images in which the packages can be built.

2. Github workflows provide an Ubuntu runner in which the `.deb` package can be built. We would have to provide self-hosted runners to build Fedora and Arch packages.

3. The AppImage is a glorified tarball built on top of a Docker manylinux version of Python. I haven't worked out how to build a distribution-ready AppImage yet, but I can hack one together that works locally.

4. For people running Ubuntu, a `.deb` package is more convenient as well as more efficient than an AppImage. The main advantage of an AppImage over a native package is that it is portable across distros. It can also be run without root access, which has some security benefits.

5. There are alternatives to AppImage, including FlatPak and ZeroInstall. Their purposes seem broadly similar. As far as I can tell the AppImage tools seem mature enough to get Python apps working so I have not investigated these alternatives any further.

6. A minimal strategy would be to provide an AppImage only. I think this is also sufficient for AYAB. But since I have already written an Ubuntu build workflow, we could distribute that as well with minimal extra effort.

**Comment by t0mpr1c3** [comment]
I suppose we should probably also delete `resources_rc.py` and generate it from `resources_rc.qrc`?

**Comment by t0mpr1c3** [comment]
There is some useful code here: https://github.com/trappitsch/fbs-release-github-actions

I will try to adapt some of this for AYAB. In particular, the Mac OS build.

**Comment by t0mpr1c3** [comment]
I have been able to complete Arch and Fedora builds locally but not using github workflows (yet).

The Mac OSX build seems to work on the github runners, but I haven't tested the package. `avrdude` can be installed using `homebrew`.

**Comment by t0mpr1c3** [comment]
I'm thinking that this script should also create the user directory for patterns. (https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/289)

**Comment by t0mpr1c3** [comment]
I think this can be closed. The AppImage covers the bases for the linux distros and can incorporate avrdude, if we even need that going forward.
