### ISSUE TITLE
Publish an alpha/beta

### ISSUE THREAD

**Issue by clholgat** [AllYarnsAreBeautiful/ayab-desktop#450]
Make an early version of the latest 1.0 desktop software and firmware available to the outside of world. When and how to do this is still up for debate.

**Comment by t0mpr1c3** [comment]
Agree

**Comment by t0mpr1c3** [comment]
Personally I suggest that we need all bugfixes and features that are going to be in the release and at least some minimal documentation of the new features, but we don't necessarily need the documentation to be fully fleshed out because we can probably give testers a bit of help online or on the discord server.

**Comment by t0mpr1c3** [comment]
@dl1com haven't we done this before, with pre-release versions?

**Comment by X-sam** [comment]
Well we have an alpha/beta plan now- [gdoc link]( https://docs.google.com/document/d/1rF4b7nMgYnvl4S0K8xNG9p6tdWAaYJtKA_X2IU2J2K0/edit#heading=h.9bas2mjrke2l)
So I'm marking this as done.
