### ISSUE TITLE
The alignment selector has no apparent effect

### ISSUE THREAD

**Issue by jonathanperret** [AllYarnsAreBeautiful/ayab-desktop#671]
To reproduce (tested on `0.99.0-rc6` on an M1 Mac):
- open AYAB
- load an image less than 200 pixels wide
- increase start and stop needle values to give the pattern space to be moved left or right
- change the Alignment value from Center to either Left or Right

Expected behavior: the main view reflects the pattern moving to the left or right of the selected area.

Observed behavior: nothing visible happens.

https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/300823/4d2deea3-790b-4c4b-982f-04d1a04f3789

**Comment by Adrienne200** [comment]
I had been looking at the alignment feature today too, even before I noticed that this issue had been logged, and that you have coded a fix for it. 
FYI Video attached here shows how it previously worked in 0.95. It did more than currently in rc6, so we need to get the next build at least back there.

But more fundamentally, is this even a useful feature? I have never used it in real life, I leave mine set to Center all the time and adjust my image either while creating it in Gimp or wherever, or using the Start/Stop needles. Left/right alignment has been in AYAB since the beginning but I don't know if anyone uses it, or what for. We could ask our Beta users. I considered proposing that we remove it altogether,  but that's probably not a good idea, better to just put it back the way it was. And redesign it (not for 1.0) for example so you can slide the whole image sideways to wherever you want it.

https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/24358225/c3fb93ba-a7f5-45f3-8358-be9b1bdab25c

**Comment by jonathanperret** [comment]
As a brand-new user (and machine knitter, for that matter) I can't comment on whether the feature is useful. As a software developer on the other hand, I am eager to remove any complexity that carry its own weight, so if it can be ascertained that this does not, I'll gladly help remove it. Agreed though that this should not block 1.0.

In any case, here's the same sequence of actions as in your movie, done on `1.0.0-dev` including my fix in #672:

https://github.com/AllYarnsAreBeautiful/ayab-desktop/assets/300823/851cb543-636a-429d-9173-6c33a776b0c6

This looks correct to me. The 1-pixel shift you can see in 0.95 when switching alignment at the start, when 96 needles are at work, looks like a bug to me, so the fact that it is gone seems an improvement.

**Comment by jonathanperret** [comment]
By the way, anyone can test the fixed behavior with this build: https://github.com/jonathanperret/ayab-desktop/releases/tag/0.99.0-alignmentfix20240629
